# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-19 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technologies',
        ),
    ]
